### ISSUE TITLE
Knowledge graph and run_Speed_up.py Error

### ISSUE THREAD

**Issue by drob2727** [KennthShang/HostG#7]
Traceback (most recent call last):
  File "run_phage_host.py", line 64, in <module>
    _ = subprocess.check_call(blast_cmd, shell=True)
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'blastn -query out/query.fa -db blast_db/bin -outfmt 6 -out blast_tab/bin.tab -num_threads 8' returned non-zero exit status 2.
folder Cyber_data/ exist... cleaning dictionary
Cannot clean your folder... permission denied
cat: pred/*: No such file or directory
folder input exist... cleaning dictionary
Dictionary cleaned
folder pred exist... cleaning dictionary
folder Split_files exist... cleaning dictionary
Dictionary cleaned
folder tmp_pred exist... cleaning dictionary
Knowledge Graph Error for file contig_0
Knowledge Graph Error for file contig_1
Knowledge Graph Error for file contig_2
Knowledge Graph Error for file contig_3
phage_host Error for file contig_4
Pre-trained CNN Error for file contig_5
Traceback (most recent call last):
  File "run_Speed_up.py", line 157, in <module>
    out = subprocess.check_call(cmd, shell=True)
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cat pred/* > final_prediction.csv' returned non-zero exit status 1.

We were so close I think. Any ideas?

**Comment by KennthShang** [comment]
Seem the format of your files in the 'bacteria' folder is incorrect. Then, BLASTN cannot run with the command "blastn -query out/query.fa -db blast_db/bin -outfmt 6 -out blast_tab/bin.tab -num_threads 8". 

You can check whether you can build the database using " makeblastdb -in bacteria/bin.fasta -dbtype nucl -parse_seqids -out blast_db/bin" and run BLASTN with your virus file.

**Comment by drob2727** [comment]
I see, so its because my files end in .fa instead of .fasta. If I fixed the file extension, can I resume from where I left off or do I have to start over?

**Comment by KennthShang** [comment]
No, it is not because of your file extension. The program can automatically read it. I mean you need to try to use makeblastdb and blastn command to debug. Because it seems the BLAST cannot run correctly.

**Comment by KennthShang** [comment]
'bin.fasta' is just an example of your input prokaryotic genomes. Since I do not know your files

**Comment by drob2727** [comment]
Building a new DB, current time: 01/16/2022 09:51:20
New DB name:   /lustre/scratch/usr/fslcollab273/HostG/blast_db/bin
New DB title:  bacteria/bin.1408.fasta
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 11 sequences in 0.048352 seconds

It looks like it can make the database so should I do this for all of my bins?

**Comment by drob2727** [comment]
How do I run the BlastN command? Thank you so much for the help

**Comment by KennthShang** [comment]
there are two dot(.) in your file name. Please use the same as the example file. accession.fa or accession.fasta. you can use dash line (_) to replace the first one. 

Also make sure your sequence in your virus fasta has at least one sequence whose length is longer than 8000bp if you use Len=8000

**Comment by KennthShang** [comment]
After solving the problem above, run two command below to check whether the BLAST can be run correctly.

makeblastdb -in bacteria/bin_1408.fasta -dbtype nucl -parse_seqids -out blast_db/bin_1408

blastn -query query.fa -db blast_db/bin_1408 -outfmt 6 -out blast_tab/bin_1408.tab -num_threads 8

query.fa is your input file.

if the are ok, then you can rerun the HostG

**Comment by drob2727** [comment]
It worked! 

(HostG) -bash-4.2$ cat bin_1408.tab
VF_VS_2402	k141_959580_length_146859_cov_1634.8330	93.846	130	7	1	8881	9009	1952	2081	9.83e-50	195
VF_VS_7541	k141_959580_length_146859_cov_1634.8330	100.000	52	0	0	200	251	71	20	1.72e-20	97.1
VF_VS_7852	k141_995934_length_49184_cov_1635.8327	81.558	385	63	7	329	711	48805	49183	5.55e-85	311
VF_VS_13436	k141_959580_length_146859_cov_1634.8330	100.000	141	0	0	1	141	141	1	4.60e-70	261
VF_VS_13436	k141_959580_length_146859_cov_1634.8330	96.296	135	5	0	2290	2424	154	20	2.17e-58	222
VF_VS_13847	k141_8453456_length_35143_cov_1469.2361	77.815	302	65	2	26	326	22545	22845	2.81e-47	185
VF_VS_14898	k141_959580_length_146859_cov_1634.8330	90.698	43	4	0	3552	3594	9502	9544	6.22e-09	58.4
VF_VS_20168	k141_959580_length_146859_cov_1634.8330	98.113	53	1	0	3451	3503	19	71	1.51e-19	93.5
VF_VS_34343	k141_995934_length_49184_cov_1635.8327	80.097	206	38	3	1	205	49097	48894	7.19e-37	150

Thats what I got, Does that look right? Should I start the process all over by deleting newly generated files?

**Comment by KennthShang** [comment]
Then, I think the program should be ok this time.

you do not need to remove them by yourself. Just rerun it should be ok

**Comment by drob2727** [comment]
Im having a hard time to understand the OSError of disk quota exceeded. I ran this with 1500 GB of Ram and I have TB of space left in my drive. Any ideas?


Traceback (most recent call last):
  File "run_phage_phage.py", line 238, in <module>
    fi = to_clusterer(ntw, out_fn+"intermediate.ntw", merged_df.copy())
  File "/lustre/scratch/usr/fslcollab273/HostG/utils.py", line 138, in to_clusterer
    with open(fi, "wt") as f:
OSError: [Errno 122] Disk quota exceeded: 'out/intermediate.ntw'
folder Cyber_data/ exist... cleaning dictionary
Dictionary cleaned
Traceback (most recent call last):
  File "run_CNN.py", line 56, in <module>
    _ = SeqIO.write(record, contig_out+name+".fasta", "fasta")
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 516, in write
    with as_handle(handle, "w") as fp:
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
OSError: [Errno 122] Disk quota exceeded: 'validation/cherry_0_196.fasta'
rm: cannot remove ‘stride50_val/*’: No such file or directory
rm: cannot remove ‘int_val/*’: No such file or directory
rm: cannot remove ‘filtered_val/*’: No such file or directory
rm: cannot remove ‘dataset/*’: No such file or directory
rm: cannot remove ‘split_long_reads_val/*’: No such file or directory
folder Cyber_data/ exist... cleaning dictionary
Traceback (most recent call last):
  File "run_CNN.py", line 56, in <module>
    _ = SeqIO.write(record, contig_out+name+".fasta", "fasta")
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 516, in write
    with as_handle(handle, "w") as fp:
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
OSError: [Errno 122] Disk quota exceeded: 'validation/cherry_0_0.fasta'
rm: cannot remove ‘validation/*’: No such file or directory
rm: cannot remove ‘stride50_val/*’: No such file or directory
rm: cannot remove ‘int_val/*’: No such file or directory
rm: cannot remove ‘filtered_val/*’: No such file or directory
rm: cannot remove ‘dataset/*’: No such file or directory
rm: cannot remove ‘split_long_reads_val/*’: No such file or directory
folder Cyber_data/ exist... cleaning dictionary
Traceback (most recent call last):
  File "run_CNN.py", line 56, in <module>
    _ = SeqIO.write(record, contig_out+name+".fasta", "fasta")
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 516, in write
    with as_handle(handle, "w") as fp:
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
OSError: [Errno 122] Disk quota exceeded: 'validation/cherry_0_0.fasta'
rm: cannot remove ‘validation/*’: No such file or directory
rm: cannot remove ‘stride50_val/*’: No such file or directory
rm: cannot remove ‘int_val/*’: No such file or directory
rm: cannot remove ‘filtered_val/*’: No such file or directory
rm: cannot remove ‘dataset/*’: No such file or directory
rm: cannot remove ‘split_long_reads_val/*’: No such file or directory
folder Cyber_data/ exist... cleaning dictionary
Traceback (most recent call last):
  File "run_CNN.py", line 56, in <module>
    _ = SeqIO.write(record, contig_out+name+".fasta", "fasta")
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 516, in write
    with as_handle(handle, "w") as fp:
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
OSError: [Errno 122] Disk quota exceeded: 'validation/cherry_0_0.fasta'
cat: pred/*: No such file or directory
folder input exist... cleaning dictionary
folder pred exist... cleaning dictionary
folder Split_files exist... cleaning dictionary
folder tmp_pred exist... cleaning dictionary
Knowledge Graph Error for file contig_0
phage_phage Error for file contig_1
Pre-trained CNN Error for file contig_2
Pre-trained CNN Error for file contig_3
Pre-trained CNN Error for file contig_4
Pre-trained CNN Error for file contig_5
Traceback (most recent call last):
  File "run_Speed_up.py", line 157, in <module>
    out = subprocess.check_call(cmd, shell=True)
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cat pred/* > final_prediction.csv' returned non-zero exit status 1.

**Comment by KennthShang** [comment]
Ummmmmm.

If you are using an HPC, you can check it out with the command "quota". Since there are two types of 'Disk quota exceeded': files or size. You might be able to find out something.

However, if you are using your own computer, I am afraid that I do not know much about this.

A simple way to test is using a smaller file. For example, you can split your file into a smaller one to run as an example and check whether there exist any bugs.

**Comment by drob2727** [comment]
Creating blast database...
Running blastn...
Creating blast database...
Running blastn...
run_KnowledgeGraph.py:100: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  node_feature = np.array(node_feature)
folder GCN_data exist... cleaning dictionary
Traceback (most recent call last):
  File "run_KnowledgeGraph.py", line 155, in <module>
    taxa_label(taxa)
  File "run_KnowledgeGraph.py", line 125, in taxa_label
    tmpL = label_df[label_df['accession'] == node.split('.')[0]][taxa].values[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
cat: pred/*: No such file or directory
folder input exist... cleaning dictionary
Dictionary cleaned
folder pred exist... cleaning dictionary
folder Split_files exist... cleaning dictionary
Dictionary cleaned
folder tmp_pred exist... cleaning dictionary
Knowledge Graph Error for file contig_0
Knowledge Graph Error for file contig_1
Traceback (most recent call last):
  File "run_Speed_up.py", line 157, in <module>
    out = subprocess.check_call(cmd, shell=True)
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cat pred/* > final_prediction.csv' returned non-zero exit status 1.

I'm having a slightly different knowledge graph error. Any ideas?

**Comment by KennthShang** [comment]
It seems you forget to add the taxonomy labels of your prokaryotes in **dataset/label.csv**.

BTW, according to your previous description, you may not know the taxonomy labels of your bins. In this situation, you can directly use names like "bin_1408" as their labels. However, we cannot ensure the model can work well. This is because HostG is a multi-class classification classifier, if the number of samples is very small, it might not be able to learn from them. But you can try.

Another solution is using our newly developed method called: [Cherry](https://github.com/KennthShang/CHERRY). We tried to fix the aforementioned problem in this new work. The usage is nearly the same but has a new formulation. You can follow the guidelines and run it at the same time.

Best,
Jiayu

**Comment by drob2727** [comment]
I’ll look through it, but I do have taxonomy in the label.csv file. Maybe it’s better to just have the contigs match up with the bin names and then use my own taxonomy file since it doesn’t seems to be working. I’ll go through it again and see if there’s any discrepancies between my taxonomy file and what it is supposed to me. I’ll send a screenshot.

Thank you so much

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by KennthShang** [comment]
I see.

The program will treat the file names (except for the '.fasta') in the 'bacteria/' folder as the accession names. 

For example, in the program

```
tmpL = label_df[label_df['accession'] == node.split('.')[0]][taxa].values[0]
```
node.split('.')[0] is bin_1408, then it will search label.csv to return its labels. 

Sorry for the inconvenience. Maybe you can also try a small sample for testing first. It will save time to construct the knowledge graph (which is an O(N^2) algorithm. 

Best,
Jiayu

**Comment by drob2727** [comment]
Makes sense to me. The way it's set up right now is like that if I'm following correctly, it says bin_1408 and then the taxonomy. Is that wrong?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by KennthShang** [comment]
Yes. So what you need to add into the label.csv is like (just an example)
```
accession,phylum,class,order,family,genus
bin_1408,Proteobacteria,Betaproteobacteria,Burkholderiales,Alcaligenaceae,Achromobacter
```
*accession,phylum,class,order,family,genus* is the header, no need to add this line.

Best,
Jiayu

**Comment by drob2727** [comment]
Ok gotcha. I will recheck my file when I get done with teaching today and I will verify. I really appreciate the help. We’re predicting hosts for our viruses from Antarctica. We’ve predicted through NCBI but there’s nothing better than using our own bacterial contigs. I really appreciate all the help. If we can get this through, I look forward to using this great tool in multiple papers

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by KennthShang** [comment]
Thanks a lot.

BTW, maybe you also want to use our new method, Cherry, in the future (although it is still under review now). In our latest experiments, it can return labels down to species level and has a more precise accuracy. 

Best,
Jiayu

**Comment by drob2727** [comment]
Oh wow, I’ll take a look at it this afternoon

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by drob2727** [comment]
Everything look great after I fixed the names until this

run_KnowledgeGraph.py:100: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  node_feature = np.array(node_feature)
folder GCN_data exist... cleaning dictionary
Traceback (most recent call last):
  File "run_KnowledgeGraph.py", line 155, in <module>
    taxa_label(taxa)
  File "run_KnowledgeGraph.py", line 125, in taxa_label
    tmpL = label_df[label_df['accession'] == node.split('.')[0]][taxa].values[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
cat: pred/*: No such file or directory
folder input exist... cleaning dictionary
folder pred exist... cleaning dictionary
folder Split_files exist... cleaning dictionary
folder tmp_pred exist... cleaning dictionary
Knowledge Graph Error for file contig_0
Knowledge Graph Error for file contig_1
Traceback (most recent call last):
  File "run_Speed_up.py", line 157, in <module>
    out = subprocess.check_call(cmd, shell=True)
  File "/fslhome/fslcollab273/.conda/envs/Host/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cat pred/* > final_prediction.csv' returned non-zero exit status 1.

**Comment by KennthShang** [comment]
It seems there still exists the same problem. 

Could you send me some samples for testing? For example, can you share some of your bins (4 or 5 of them?), if they are not private and too large. Then, I can test it on my HPC.

If you want, you can send them (or the link) to my email: jyshang2-c@my.cityu.edu.hk

Best,
Jiayu

**Comment by KennthShang** [comment]
Hi, I have checked your data, it seems everything works well. The output of the examples like below:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/22445402/152128790-05ae337f-7cd2-4fa7-8a8f-28a3cc965582.png">


Please check whether you have added the taxa like below (in **label.csv**):
<img width="504" alt="image" src="https://user-images.githubusercontent.com/22445402/152128375-92cc83c6-60a9-413f-a495-09ff3349c0b8.png">

Since I do not know the exact taxa, I use *temp* instead. You can also run the example files you sent me to test whether the program can work correctly on your PC/HPC

Best,
Jiayu

**Comment by drob2727** [comment]
Thank you so much for looking at that. I think it has to be my label.csv file that's wrong. Ill send a picture
________________________________

**Comment by drob2727** [comment]
<img width="637" alt="Screen Shot 2022-02-07 at 10 42 08 AM" src="https://user-images.githubusercontent.com/64169649/152842658-dd719d57-983d-4e3c-a4aa-813b9b28e194.png">


This is what my label.csv file looks like. Is it the NA and no support thats giving me trouble? I tried to fix a couple things and then resubmit and it still had problems.
